spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class_attendance?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  file: /export/log
  level: info

